export const METADATA_KEYS = {
    CONTROLLER: "custom:controller",
    METHOD: "custom:method",
    PATH: "custom:path",
    BASE_PATH: "custom:base-path",
    TAGS: "custom:tags",
    HEADERS: "custom:headers",
    BODY: "custom:body",
    RESPONSES: "custom:responses",
    MIDDLEWARES: "custom:middlewares",
    GUARDS: "custom:guards",
    REQUIRES_AUTH: "custom:requires-auth",
    API_PROPERTIES: "custom:api-properties",
    DESCRIPTION: "custom:description",
    QUERY: "custom:query",
};
